/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"

import { useTexture, useGLTF, MeshRefractionMaterial } from "@react-three/drei"

function Background() {
  const texture = useTexture("./textures/sky_an_horizon_with_clouds.jpg")
  texture.wrapS = THREE.RepeatWrapping
  texture.wrapT = THREE.RepeatWrapping
  texture.repeat.set(2, 2)
  return (
    <mesh
      rotation={[-0.7, 0, 0]}
      scale={50}
    >
      <sphereGeometry />
      <meshBasicMaterial
        map={texture}
        depthTest={false}
        side={THREE.BackSide}
      />
    </mesh>
  )
}

export function A_blooming(props) {
  const { nodes, materials } = useGLTF("./models/A_diamant.glb")
  const texture = useTexture("./textures/sky_an_horizon_with_clouds.jpg")
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.diamant.geometry}
        position={[0, 0.5, 0]}
        rotation={[-1.64, 0, 3.12]}
        scale={0.4}
      >
        <MeshRefractionMaterial
          bounces={3}
          aberrationStrength={0.01}
          envMap={texture}
          toneMapped={false}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload("./models/dflat.glb")
