/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function A_diamant(props) {
  const { nodes, materials } = useGLTF("./models/A_diamant.gltf")
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.diamant.geometry}
        material={materials.dia}
        position={[0, 0.5, 0]}
        rotation={[-1.64, 0, 3.12]}
        scale={0.4}
      />
    </group>
  )
}

useGLTF.preload("/models/A_diamant.gltf")
