/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef, useEffect } from "react";
import {
  useGLTF,
  MeshPortalMaterial,
  Environment,
  useTexture,
  RoundedBox,
} from "@react-three/drei";
import * as THREE from "three";


// export function A_ecrin_bas3(props) {
export const A_ecrin_bas3 = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("./models/A_ecrin_bas.gltf");
  const map = useTexture(
    "../../public/textures/radiant_rocks_in_thje_jungle.jpg"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh ref={ref} geometry={nodes.objectBas.geometry} material={materials.Ecrin}>
          <mesh ref={ref} geometry={nodes.faceBasse.geometry} material={materials.Ecrin}>
            <MeshPortalMaterial>
              <ambientLight intensity={0.1} />
              <Environment preset={"dawn"} />
              <mesh>
                <sphereGeometry args={[5, 32, 32]} rotation={[0,Math.PI / 2,  0]} />

                <meshStandardMaterial map={map} side={THREE.BackSide} />
              </mesh>
            </MeshPortalMaterial>
          </mesh>
        </mesh>
      </group>
    </group>
  );
})

useGLTF.preload("/models/A_ecrin_bas.gltf");
