/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function A_ecrin_bas(props) {
  const { nodes, materials } = useGLTF("./models/A_ecrin_bas.gltf")
  return (
    <group
      {...props}
      dispose={null}
    >
      <group rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh
          geometry={nodes.faceBasse.geometry}
          material={materials.dia}
        />
        <mesh
          geometry={nodes.objectBas.geometry}
          material={materials.Ecrin}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/A_ecrin_bas.gltf")
