/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import {
  useGLTF,
  MeshPortalMaterial,
  Environment,
  useTexture,
} from "@react-three/drei"
import * as THREE from "three"

export function B_ecrin_bas(props) {
  const { nodes, materials } = useGLTF("/models/B_ecrin_bas.gltf")
  const map = useTexture(
    "../../public/textures/radiant_rocks_in_thje_jungle.jpg"
  )
  return (
    <group
      {...props}
      dispose={null}
    >
      <group
        position={[0, -0.72, 1.27]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes.faceBasse.geometry}
          material={materials.dia}
        >
          <MeshPortalMaterial>
            <ambientLight intensity={0.1} />
            <Environment preset={"dawn"} />
            <mesh>
              <sphereGeometry
                args={[5, 32, 32]}
                rotation={[0, Math.PI / 2, 0]}
              />

              <meshStandardMaterial
                map={map}
                side={THREE.BackSide}
              />
            </mesh>
          </MeshPortalMaterial>
        </mesh>
        <mesh
          geometry={nodes.objectBas.geometry}
          material={materials.Ecrin}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/B_ecrin_bas.gltf")
