/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function DiamantA(props) {
  const { nodes, materials } = useGLTF("/models/diamantA.gltf")
  return (
    <group
      {...props}
      dispose={null}
    >
      <group rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh
          geometry={nodes.faceBasse.geometry}
          material={materials.dia}
        />
        <mesh
          geometry={nodes.objectBas.geometry}
          material={materials.Ecrin}
        />
        <group
          position={[-0.16, 0, -0.42]}
          rotation={[0, -0.31, 0]}
        >
          <mesh
            geometry={nodes.faceHaute.geometry}
            material={materials.dia}
          />
          <mesh
            geometry={nodes.objetHaut.geometry}
            material={materials.Ecrin}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.diamant.geometry}
        material={materials.dia}
        position={[0, 0.5, 0]}
        rotation={[-1.64, 0, 3.12]}
        scale={[0.3, 0.4, 1.64]}
      />
    </group>
  )
}

useGLTF.preload("/models/diamantA.gltf")
