/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"

export function exportBlender(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/models/exportBlender.gltf")
  const { actions } = useAnimations(animations, group)
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
    >
      <group name='Scene'>
        <mesh
          name='pSuperShape1'
          geometry={nodes.pSuperShape1.geometry}
          material={materials.lambert1}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/exportBlender.gltf")
