/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"

export function NinjaB(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/models/NinjaB.gltf")
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  useEffect(() => {
    actions["Idle"].reset().fadeIn(0.5).play()
    return () => actions["Death"].fadeOut(0.5)
  }, [])
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
    >
      <group name='Scene'>
        <group name='CharacterArmature'>
          <primitive object={nodes.Root} />
          <group name='Ninja'>
            <skinnedMesh
              name='Cube001'
              geometry={nodes.Cube001.geometry}
              material={materials["Ninja_Main.001"]}
              skeleton={nodes.Cube001.skeleton}
            />
            <skinnedMesh
              name='Cube001_1'
              geometry={nodes.Cube001_1.geometry}
              material={materials["Ninja_Secondary.001"]}
              skeleton={nodes.Cube001_1.skeleton}
            />
            <skinnedMesh
              name='Cube001_2'
              geometry={nodes.Cube001_2.geometry}
              material={materials["Belt.001"]}
              skeleton={nodes.Cube001_2.skeleton}
            />
            <skinnedMesh
              name='Cube001_3'
              geometry={nodes.Cube001_3.geometry}
              material={materials["Gold.001"]}
              skeleton={nodes.Cube001_3.skeleton}
            />
            <skinnedMesh
              name='Cube001_4'
              geometry={nodes.Cube001_4.geometry}
              material={materials["Eye_Black.002"]}
              skeleton={nodes.Cube001_4.skeleton}
            />
            <skinnedMesh
              name='Cube001_5'
              geometry={nodes.Cube001_5.geometry}
              material={materials["Eye_White.002"]}
              skeleton={nodes.Cube001_5.skeleton}
            />
            <skinnedMesh
              name='Cube001_6'
              geometry={nodes.Cube001_6.geometry}
              material={materials["Birb_Secondary.001"]}
              skeleton={nodes.Cube001_6.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/models/NinjaB.gltf")
