/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react"
import {
  useTexture,
  useGLTF,
  MeshRefractionMaterial,
  useAnimations,
} from "@react-three/drei"

export function Stars(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("./models/stars.gltf")

  function Background() {
    const texture = useTexture("./textures/surreal_scary_mountains.jpg")
    texture.wrapS = THREE.RepeatWrapping
    texture.wrapT = THREE.RepeatWrapping
    texture.repeat.set(2, 2)
    return (
      <mesh
        rotation={[-0.7, 0, 0]}
        scale={50}
      >
        <sphereGeometry />
        <meshBasicMaterial
          map={texture}
          depthTest={false}
          side={THREE.BackSide}
        />
      </mesh>
    )
  }

  const texture = useTexture("./textures/surreal_scary_mountains.jpg")
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
    >
      <group name='Scene'>
        <mesh
          name='pSuperShape1'
          geometry={nodes.pSuperShape1.geometry}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <MeshRefractionMaterial
            bounces={1}
            aberrationStrength={0.01}
            envMap={texture}
            toneMapped={false}
          />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload("/models/stars.gltf")
