/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"

export function Stars(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/models/stars.gltf")
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  useEffect(() => {
    actions["idle0"].reset().fadeIn(0.5).play()
    return () => actions["idle0"].fadeOut(0.5)
  }, [])
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
    >
      <group name='Scene'>
        <mesh
          name='pSuperShape1'
          geometry={nodes.pSuperShape1.geometry}
          material={materials["lambert1.001"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("/models/stars.gltf")
